### ISSUE TITLE
Process name list needs an update for 4.x

### ISSUE THREAD

**Issue by jeremyeder** [redhat-performance/pbench-analyzer#8]
https://github.com/redhat-performance/pbench-analyzer/blob/6c668bf1d112218903193c19e4f72dfcfba71f4b/cmd/scraper/main.go#L15

**Comment by jeremyeder** [comment]
openshift-kube-apiserver
etcd
kubelet
openshift-apiserver
cluster-kube-apiserver
machine-config-server
crio
ovs
kube-scheduler
openshift-network-controller
machine-controller-manager
kube-controller-manager
auth-operator
coredns
node-exporter
olm-operators
service-serving-cert-signer
autoscaler-operator
machine-config-controller
tuned
package-server
machine-config-daemon
machine-healthcheck

**Comment by sjug** [comment]
Fixed in https://github.com/redhat-performance/pbench-analyzer/pull/9

**Comment by jeremyeder** [comment]
need to add prometheus to this

**Comment by sjug** [comment]
Already has prometheus in the original list (and still does in the PR #9 ).
